/** Rotas de ações (botões de cadastro, despacho, exportação, etc.) */
export const ACTION_ROUTES = {
  vehiclesRegister: "/vehicles/register",
  vehiclesAssign: "/travels/assign",
  driversRegister: "/drivers/register",
  fuelRegister: "/fuel/register",
  travelsRegister: "/travels/register",
  travelsAssign: "/travels/assign",
  travelsMatching: "/travels/matching",
  travelsSuggestions: "/travels/suggestions",
  maintenanceRegister: "/maintenance/register",
  maintenanceSchedule: "/maintenance/schedule",
  logisticsDispatch: "/logistics/dispatch",
  inspectionRegister: "/inspection/register",
  inspectionNew: "/inspection/new",
  inspectionDetail: "/inspection/detail",
  dashboardRegister: "/vehicles/register",
  dashboardExport: "/reports/export",
  cockpitOrder: "/travels/register",
  partnersRegister: "/partners/register",
  partnersSupport: "/partners/support",
  partnersDocs: "/partners/docs",
  reportsExport: "/reports/export",
  aiSecurityVisual: "/ai-security/visual",
  aiSecurityEvidence: "/ai-security/evidence",
  aiSecurityPlan: "/ai-security/plan",
  registerAccount: "/register",
  apiDocs: "http://localhost:3001/api-docs",
} as const;
